### ISSUE TITLE
colors do not align with with current catppuccin palette

### ISSUE THREAD

**Issue by alexdauenhauer** [catppuccin/iterm#21]
https://github.com/catppuccin/iterm/pull/20

related PR that I closed. Not sure why, but the colors are not correct. When I import the hex values are not aligned with the correct hex values

**Comment by MatthiasPortzel** [comment]
This is because the Apple color selector is displaying P3 colors by default. P3 is a color profile created by Apple that supports more colors than sRGB which is “normal” (what the catppuccin repo lists the hex codes as). You should see a little “P3” to the left of the hex code box. If you click the icon that looks like a sheet of paper under the hex box to open the pop-out color selector, go to the RGB sliders, and click the 3 dots in the top right, you can choose the color profile and set it back to sRGB.

Thanks for checking because this color profile stuff is confusing and it’s possible that we or iTerm messed it but I think it’s currently correct.

**Comment by alexdauenhauer** [comment]
oh wow I had no idea! thanks for the info!
