### ISSUE TITLE
Color looks wrong

### ISSUE THREAD

**Issue by Ridermansb** [catppuccin/iterm#23]
After applying the colors.. doesn't sounds that is working..

![image](https://github.com/user-attachments/assets/4fb49cc3-8465-411d-843a-3c309642c722)

**Comment by MatthiasPortzel** [comment]
All the themes have Latte as their light variant. Since macOS is using a light system theme and you have "Use different colors for light and dark mode" checked, iTerm is using the Latte light colors instead of the macchiato colors. To fix it:
1. select "Editing: Dark Mode" in that panel, then
2. uncheck "Use different colors for light and dark mode." (Whether you're editing light or dark effects which one will be used when the box is unchecked.)

(This is confusing, not your fault.)

**Comment by Ridermansb** [comment]
Thanks @MatthiasPortzel .. working now.

**Comment by ksandvik** [comment]
Yes I stumbled upon this myself one hour ago, but thanks for the info. This should definitely be in the FAQ. Most of my dark mode iTerm settings are named dark so this way I know which ones to select. Feel free to close this one.

**Comment by jby** [comment]
@MatthiasPortzel - the above tip did not solve it for me.
If I follow the instructions it reverts to my previous imported color scheme (Dracula), when I do point 2, upon choosing Catppuccin in the list still shows the light version...
